FROM ubuntu:20.04

#set up envrioment
RUN apt-get update && apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs g++ build-essential

#setup the app itself.
RUN mkdir /workspace
WORKDIR /workspace
CMD npm install && npm run dev
